"KeyValue"
{
	"HEALTH"
	{
		"string"								"health"
		"type"									"NONE"
		"localization"							"$health"
		"localization_desc"						""
		"multiple"								""
		"settle"								""
		"check_value"							""
		"generate_function"						"1"
	}
	"ATTACK"
	{
		"string"								"attack"
		"type"									"NONE"
		"localization"							"$attack"
		"localization_desc"						""
		"multiple"								""
		"settle"								""
		"check_value"							""
		"generate_function"						"1"
	}
}
