/** @noSelfInFile */
enum EOMModifierFunction {
	/** $health */
	EOM_MODIFIER_PROPERTY_HEALTH = modifierfunction.MODIFIER_FUNCTION_LAST + 1,
	/** 三围提供的生命值 */
	EOM_MODIFIER_PROPERTY_HEALTH_STATS,
	/** %$health */
	EOM_MODIFIER_PROPERTY_HEALTH_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_HEALTH_PERCENTAGE_MULTIPLE,
	/** %$teamhero$health */
	EOM_MODIFIER_TEAMHERO_PROPERTY_HEALTH_PERCENTAGE,
	/** $hp_regen */
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT,
	/** 三围提供的生命回复 */
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT_STATS,
	/** %最大生命恢复 */
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE,
	/** %生命恢复增强 */
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_AMPLIFY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_REDUCTION_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_HEALTH_REGEN_MULTIPLE,
	/** 每点力量提供生命值 */
	EOM_MODIFIER_PROPERTY_HEALTH_PER_STRENGTH,
	EOM_MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_HEAL_REDUCTION_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_HEAL_MULTIPLE,
	/** $mana */
	EOM_MODIFIER_PROPERTY_MANA,
	/** 三围提供的魔法值 */
	EOM_MODIFIER_PROPERTY_MANA_STATS,
	/** %$mana */
	EOM_MODIFIER_PROPERTY_MANA_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_MANA_PERCENTAGE_MULTIPLE,
	/** $mana_regen */
	EOM_MODIFIER_PROPERTY_MANA_REGEN_CONSTANT,
	/** 三围提供的魔法回复 */
	EOM_MODIFIER_PROPERTY_MANA_REGEN_CONSTANT_STATS,
	/** %最大魔法恢复 */
	EOM_MODIFIER_PROPERTY_MANA_REGEN_PERCENTAGE,
	/** %魔法恢复增强 */
	EOM_MODIFIER_PROPERTY_MANA_REGEN_AMPLIFY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_MANA_REGEN_REDUCTION_PERCENTAGE,
	/** %魔法消耗* */
	EOM_MODIFIER_PROPERTY_MANACOST_PERCENTAGE,
	/** $damage */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE,
	/** 三围提供的攻击力 */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_STATS,
	/** %$damage */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PERCENTAGE_MULTIPLE,
	/** 额外攻击力，不会受到任何百分比影响 */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_EXTRA,
	/** 每点敏捷提供攻击力 */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PER_AGILITY,
	/** $teamhero$damage */
	EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_DAMAGE,
	/** %$teamhero$damage */
	EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ATTACK_SPELL_POWER_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PROC,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_ADAPTIVE,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_ADAPTIVE_TARGET,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_POST_CRIT,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PHYSICAL_POST_CRIT,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_MAGICAL_POST_CRIT,
	EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PURE_POST_CRIT,
	EOM_MODIFIER_PROPERTY_SUPPRESS_CLEAVE,
	/** 攻击不会落空，最终值大于0生效 */
	EOM_MODIFIER_PROPERTY_ATTACK_CANNOT_MISS,
	/** %攻击必中率 */
	EOM_MODIFIER_PROPERTY_ATTACK_ACCURACY,
	/** $spell_power */
	EOM_MODIFIER_PROPERTY_SPELL_POWER,
	/** 三围提供的法术强度 */
	EOM_MODIFIER_PROPERTY_SPELL_POWER_STATS,
	/** %$spell_power */
	EOM_MODIFIER_PROPERTY_SPELL_POWER_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_SPELL_POWER_PERCENTAGE_MULTIPLE,
	EOM_MODIFIER_PROPERTY_SPELL_POWER_EXTRA,
	/** $teamhero$spell_power */
	EOM_MODIFIER_TEAMHERO_PROPERTY_SPELL_POWER,
	/** %$teamhero$spell_power */
	EOM_MODIFIER_TEAMHERO_PROPERTY_SPELL_POWER_PERCENTAGE,
	/** 每点智力提供法术强度 */
	EOM_MODIFIER_PROPERTY_INTELLECT_SPELL_POWER,
	/** $armor */
	EOM_MODIFIER_PROPERTY_ARMOR,
	EOM_MODIFIER_PROPERTY_ARMOR_LEVEL,
	/** %$armor */
	EOM_MODIFIER_PROPERTY_ARMOR_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ARMOR_PERCENTAGE_MULTIPLE,
	/** 无视护甲 */
	EOM_MODIFIER_PROPERTY_IGNORE_ARMOR,
	EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_TARGET,
	/** %无视护甲 */
	EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_PERCENTAGE_TARGET,
	/** $teamhero$armor */
	EOM_MODIFIER_TEAMHERO_PROPERTY_ARMOR,
	/** %吸血概率 */
	EOM_MODIFIER_PROPERTY_LIFESTEAL_CHANCE,
	/** %物理吸血 */
	EOM_MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL,
	/** %魔法吸血 */
	EOM_MODIFIER_PROPERTY_MAGICAL_LIFESTEAL,
	/** %全能吸血 */
	EOM_MODIFIER_PROPERTY_ALL_LIFESTEAL,
	EOM_MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_LIFESTEAL_REDUCTION_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_LIFESTEAL_MULTIPLE,
	EOM_MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL_MULTIPLE,
	EOM_MODIFIER_PROPERTY_MAGICAL_LIFESTEAL_MULTIPLE,
	/** %溅射伤害 */
	EOM_MODIFIER_PROPERTY_CLEAVE_DAMAGE,
	/** 溅射范围 */
	EOM_MODIFIER_PROPERTY_CLEAVE_RADIUS,
	EOM_MODIFIER_PROPERTY_CLEAVE_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_CLEAVE_RADIUS_PERCENTAGE,
	/** $attack */
	EOM_MODIFIER_PROPERTY_ATTACKSPEED_BONUS,
	EOM_MODIFIER_PROPERTY_ATTACKSPEED_PERCENTAGE,
	/** 最大$attack */
	EOM_MODIFIER_PROPERTY_MAX_ATTACKSPEED_BONUS,
	EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACKSPEED_BONUS,
	/** $attack_range_all */
	EOM_MODIFIER_PROPERTY_ATTACK_RANGE,
	/** %$attack_range_all */
	EOM_MODIFIER_PROPERTY_ATTACK_RANGE_PERCENTAGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_RANGE,
	EOM_MODIFIER_PROPERTY_FIXED_ATTACK_RANGE,
	EOM_MODIFIER_PROPERTY_FIXED_BASE_ATTACK_RANGE,
	/** $attack_rate* */
	EOM_MODIFIER_PROPERTY_ATTACK_RATE,
	EOM_MODIFIER_PROPERTY_FIXED_ATTACK_RATE,
	EOM_MODIFIER_PROPERTY_FIXED_BASE_ATTACK_RATE,
	/** $cast_range */
	EOM_MODIFIER_PROPERTY_CAST_RANGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_CAST_RANGE,
	/** 造成伤害附加伤害，类型随主伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE,
	/** 造成伤害附加物理伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_PHYSICAL,
	/** 造成伤害附加魔法伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_MAGICAL,
	/** 造成伤害附加纯粹伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_PURE,
	/** 造成伤害附加自适应伤害，会随自适应结果变化 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_ADAPTIVE,
	/** 造成伤害附加物理伤害，不参与计算暴击 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_PHYSICAL_POST_CRIT,
	/** 造成伤害附加魔法伤害，不参与计算暴击 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_MAGICAL_POST_CRIT,
	/** 造成伤害附加纯粹伤害，不参与计算暴击 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_DAMAGE_PURE_POST_CRIT,
	/** 将伤害中的所有物理伤害转化为魔法伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PHYSICAL_CONVERT_TO_MAGICAL,
	/** 将伤害中的所有魔法伤害转化为物理伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_MAGICAL_CONVERT_TO_PHYSICAL,
	/** 造成伤害附加腐蚀倍率 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BONUS_ARMOR_REDUCTION_FACTOR,
	/** $str */
	EOM_MODIFIER_PROPERTY_STATS_STRENGTH,
	EOM_MODIFIER_PROPERTY_STATS_STRENGTH_EXTRA,
	/** %$str */
	EOM_MODIFIER_PROPERTY_STATS_STRENGTH_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_STATS_STRENGTH_PERCENTAGE_MULTIPLE,
	/** $agi */
	EOM_MODIFIER_PROPERTY_STATS_AGILITY,
	EOM_MODIFIER_PROPERTY_STATS_AGILITY_EXTRA,
	/** %$agi */
	EOM_MODIFIER_PROPERTY_STATS_AGILITY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_STATS_AGILITY_PERCENTAGE_MULTIPLE,
	/** $int */
	EOM_MODIFIER_PROPERTY_STATS_INTELLECT,
	EOM_MODIFIER_PROPERTY_STATS_INTELLECT_EXTRA,
	/** %$int */
	EOM_MODIFIER_PROPERTY_STATS_INTELLECT_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_STATS_INTELLECT_PERCENTAGE_MULTIPLE,
	/** %$teamhero$int */
	EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_INTELLECT_PERCENTAGE,
	/** $primary_attribute */
	EOM_MODIFIER_PROPERTY_STATS_PRIMARY,
	/** %$primary_attribute */
	EOM_MODIFIER_PROPERTY_STATS_PRIMARY_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_STATS_PRIMARY_PERCENTAGE_MULTIPLE,
	/** $all */
	EOM_MODIFIER_PROPERTY_STATS_ALL,
	/** %$all */
	EOM_MODIFIER_PROPERTY_STATS_ALL_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_STATS_ALL_PERCENTAGE_MULTIPLE,
	/** $teamhero$all */
	EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_ALL,
	/** 伤害百分比 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE,
	/** 必须源伤害类型为自适应，例：自适应结果为物理，但该效果不等同于增加物理伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_ADAPTIVE_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_OUTGOING_ADAPTIVE_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %物理伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %魔法伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	EOM_MODIFIER_PROPERTY_OUTGOING_PURE_DAMAGE_PERCENTAGE,
	/** %信仰圣堂点数伤害提升 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_FAITH,
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_FAITH_MULTIPLE,
	/** %圣匣中每件6级装备伤害提升 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR,
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR_MULTIPLE,
	/** %技能伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_ABILITY_DAMAGE_PERCENTAGE,
	/** %攻击伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_ATTACK_DAMAGE_PERCENTAGE,
	/** %最终伤害 */
	EOM_MODIFIER_PROPERTY_FINAL_DAMAGE,
	/** %$teamhero伤害 */
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %$teamhero物理伤害 */
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %$teamhero魔法伤害 */
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %召唤物伤害 */
	EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %$teamhero召唤物伤害 */
	EOM_MODIFIER_TEAMHERO_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE,
	/** %对金币怪伤害 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_TO_TRAINING,
	/** %召唤物减伤 */
	EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_REDUCTION,
	/** %伤害减免 */
	EOM_MODIFIER_PROPERTY_DAMAGE_REDUCTION,
	/** %受到伤害* */
	EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE,
	/** %受到伤害* */
	EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE_MULTIPLE,
	/** 受到伤害增加固定数值 */
	EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_BONUS_DAMAGE,
	/** %受到物理伤害* */
	EOM_MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE,
	/** %受到魔法伤害* */
	EOM_MODIFIER_PROPERTY_INCOMING_MAGICAL_DAMAGE_PERCENTAGE,
	/** 免死功能，使用时需要判断该次伤害是否有不致死flag，如果返回值大于0则本次伤害会自动加上不致死flag，返回值为目标最低剩余血量，如果目标本身血量低于最低血量，则会直接使用当前血量作为最低血量 */
	EOM_MODIFIER_PROPERTY_NON_LETHAL,
	/** 税前物理伤害数值修改 */
	EOM_MODIFIER_PROPERTY_PRE_PHYSICAL_DAMAGE_ADJUST,
	/** 税前魔法伤害数值修改 */
	EOM_MODIFIER_PROPERTY_PRE_MAGICAL_DAMAGE_ADJUST,
	/** 税前伤害数值修改 */
	EOM_MODIFIER_PROPERTY_PRE_DAMAGE_ADJUST,
	/** 税后物理伤害数值修改 */
	EOM_MODIFIER_PROPERTY_PHYSICAL_DAMAGE_ADJUST,
	/** 税后魔法伤害数值修改 */
	EOM_MODIFIER_PROPERTY_MAGICAL_DAMAGE_ADJUST,
	/** 税后伤害数值修改 */
	EOM_MODIFIER_PROPERTY_DAMAGE_ADJUST,
	/** 税后格挡 */
	EOM_MODIFIER_PROPERTY_DAMAGE_BLOCK,
	/** 物理护盾，等同于税后物理伤害数值修改，但是伤害显示数值为护盾计算前 */
	EOM_MODIFIER_PROPERTY_PHYSICAL_DAMAGE_BARRIER,
	/** 魔法护盾，等同于税后魔法伤害数值修改，但是伤害显示数值为护盾计算前 */
	EOM_MODIFIER_PROPERTY_MAGICAL_DAMAGE_BARRIER,
	/** 护盾，等同于税后伤害数值修改，但是伤害显示数值为护盾计算前 */
	EOM_MODIFIER_PROPERTY_DAMAGE_BARRIER,
	/** 免疫物理伤害 */
	EOM_MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PHYSICAL,
	/** 免疫魔法伤害 */
	EOM_MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_MAGICAL,
	/** 免疫纯粹伤害 */
	EOM_MODIFIER_PROPERTY_ABSOLUTE_NO_DAMAGE_PURE,
	/** 免疫伤害 */
	EOM_MODIFIER_PROPERTY_AVOID_DAMAGE,
	/** 丢失伤害 */
	EOM_MODIFIER_PROPERTY_MISS_DAMAGE,
	/** %$crit_chance */
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_CHANCE,
	/** 目标暴击概率，即目标受伤时会提高被暴击的概率 */
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_CHANCE_TARGET,
	/** %$crit_damage */
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE,
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE,
	/** 目标暴击伤害，即目标受到暴击时会提高被暴击的伤害 */
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_TARGET,
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_TARGET_MULTIPLE,
	/** 固定暴击率，将暴击概率锁定为一个数值 */
	EOM_MODIFIER_PROPERTY_FIXED_CRITICALSTRIKE_CHANCE,
	/** %$teamhero$crit_chance */
	EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_CHANCE,
	/** %$teamhero$crit_damage */
	EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE,
	EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE,
	/** 不再触发暴击，返回值大于0有效 */
	EOM_MODIFIER_PROPERTY_NO_CRITICALSTRIKE,
	/** %冷却缩减 */
	EOM_MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE,
	/** 减少固定冷却时间 */
	EOM_MODIFIER_PROPERTY_COOLDOWN_REDUCTION_CONSTANT,
	/** %$evasion */
	EOM_MODIFIER_PROPERTY_EVASION_CONSTANT,
	/** 冲刺最大充能 */
	EOM_MODIFIER_PROPERTY_DASH_CHARGES,
	/** %冲刺距离 */
	EOM_MODIFIER_PROPERTY_DASH_PERCENTAGE,
	/** 冲刺距离 */
	EOM_MODIFIER_PROPERTY_DASH_CONSTANT,
	/** %冲刺充能效率 */
	EOM_MODIFIER_PROPERTY_DASH_CHARGE_SPEED,
	/** <corrosion:腐蚀值/> */
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION,
	/** %<corrosion:腐蚀值/> */
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE,
	/** 目标腐蚀值百分比，即目标受到腐蚀效果时会提高的被腐蚀值百分比 */
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_TARGET,
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_TARGET_MULTIPLE,
	/** 召唤物攻击速度 */
	EOM_MODIFIER_PROPERTY_SUMMONED_ATTACKSPEED,
	/** 修改攻击音效合集名字，一般用于变身 */
	EOM_MODIFIER_PROPERTY_ATTACK_SOUND_SET,
	/** 修改攻击音效名字 */
	EOM_MODIFIER_PROPERTY_ATTACK_SOUND,
	/** 修改弹道命中音效名字，仅支持有攻击远程弹道 */
	EOM_MODIFIER_PROPERTY_PROJECTILE_IMPACT_SOUND,
	/** %眩晕时间加成 */
	EOM_MODIFIER_PROPERTY_STUN_TIME_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_CHILL_PERCENTAGE,
	/** %降低冻结单位生命恢复 */
	EOM_MODIFIER_PROPERTY_CHILL_RECUDE_HEALTH_REGEN_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_FREEZE_TIME_PERCENTAGE,
	/** %控制条累计加成 */
	EOM_MODIFIER_PROPERTY_CONTROL_THRESHOLD_PERCENTAGE,
	/** %护盾加成 */
	EOM_MODIFIER_PROPERTY_BARRIER_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_PUNCTURE_DAMAGE_PERCENTAGE,
	/** %流血幅度 */
	EOM_MODIFIER_PROPERTY_BLEEDING_DAMAGE_PERCENTAGE,
	/** %流血速率 */
	EOM_MODIFIER_PROPERTY_BLEEDING_RATE_PERCENTAGE,
	/** 流血持续时间 */
	EOM_MODIFIER_PROPERTY_BLEEDING_DURATION,
	/** 流血叠加上限 */
	EOM_MODIFIER_PROPERTY_BLEEDING_STACK,
	/** %流血治疗 */
	EOM_MODIFIER_PROPERTY_BLEEDING_LIFESTEAL,
	/** %燃烧幅度 */
	EOM_MODIFIER_PROPERTY_BURNING_BASE_DAMAGE_PERCENTAGE,
	/** %燃烧伤害 */
	EOM_MODIFIER_PROPERTY_BURNING_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_BURNING_DAMAGE_PERCENTAGE_TARGET,
	/** %燃烧速率 */
	EOM_MODIFIER_PROPERTY_BURNING_RATE_PERCENTAGE,
	/** 燃烧持续时间 */
	EOM_MODIFIER_PROPERTY_BURNING_DURATION,
	/** %持续伤害 */
	EOM_MODIFIER_PROPERTY_DOT_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_GAME_BASE_DAMAGE_REDUCTION,
	/** %传说武具升阶所需能量点数 */
	EOM_MODIFIER_PROPERTY_TEARS_OF_ATHENA_COUNT_MODIFY_PERCENT,
	EOM_MODIFIER_PROPERTY_BREATHE_FIRE_DAMAGE_PERCENTAGE,
	/** %<invisibility:隐身/>时伤害 */
	EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %<invisibility:隐身/>时减伤 */
	EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_REDUCTION,
	/** %<invisibility:隐身/>时<corrosion:腐蚀值/> */
	EOM_MODIFIER_PROPERTY_INVISIBILITY_ARMOR_REDUCTION_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_INVISIBILITY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE,
	/** %<damage_immune:伤害免疫/>时伤害 */
	EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DAMAGE_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DAMAGE_PERCENTAGE_MULTIPLE,
	/** %<damage_immune:伤害免疫/>持续时间 */
	EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DURATION_PERCENTAGE,
	/** 击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL,
	/** %击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫白羊座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_ARIES_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫金牛座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_TAURUS_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫双子座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_GEMINI_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫巨蟹座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_CANCER_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫狮子座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_LEO_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫处女座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_VIRGO_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫天秤座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_LIBRA_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫天蝎座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_SCORPIO_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫射手座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_SAGITTARIUS_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫摩羯座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_CAPRICORN_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫水瓶座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_AQUARIUS_GOLD_PER_KILL_PERCENTAGE,
	/** %十二星宫双鱼座赐福等级增加击杀获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_PISCES_GOLD_PER_KILL_PERCENTAGE,
	/** 击杀获得$crystal */
	EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL,
	/** %击杀获得$crystal */
	EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL_PERCENTAGE,
	/** 击杀获得$score */
	EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL,
	/** %击杀获得$score */
	EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL_PERCENTAGE,
	/** %击杀获得资源 */
	EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE_MULTIPLE,
	/** 击杀提高$health */
	EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_KILL,
	/** 击杀提高$damage */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_KILL,
	/** 击杀提高$spell_power */
	EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_KILL,
	/** 击杀提高$all */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_KILL,
	/** 击杀提高$str */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_KILL,
	/** 击杀提高$agi */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_KILL,
	/** 击杀提高$int */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_KILL,
	/** %击杀提高属性 */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_MULTIPLE,
	/** 每秒提高$str */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_SEC,
	/** 每秒提高$agi */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_SEC,
	/** 每秒提高$int */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_SEC,
	/** 每秒提高$all */
	EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_SEC,
	/** 每秒提高$health */
	EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_SEC,
	/** 每秒提高$damage */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_SEC,
	/** 每秒提高$spell_power */
	EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_SEC,
	/** %每分钟提高伤害 */
	EOM_MODIFIER_PLAYER_PROPERTY_DAMAGE_PER_MIN,
	/** %每分钟提高物理伤害 */
	EOM_MODIFIER_PLAYER_PROPERTY_PHYSICAL_DAMAGE_PER_MIN,
	/** %每分钟提高魔法伤害 */
	EOM_MODIFIER_PLAYER_PROPERTY_MAGICAL_DAMAGE_PER_MIN,
	/** %每分钟提高暴击伤害 */
	EOM_MODIFIER_PLAYER_PROPERTY_CRITICALSTRIKE_DAMAGE_PER_MIN,
	/** %随时间提高属性 */
	EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE_MULTIPLE,
	/** %$team随时间提高属性 */
	EOM_MODIFIER_TEAM_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE,
	/** 每秒获得$gold */
	EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_SEC,
	/** 每秒获得$crystal */
	EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_SEC,
	/** 每秒获得$score */
	EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_SEC,
	/** %随时间获得资源 */
	EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE_MULTIPLE,
	EOM_MODIFIER_PLAYER_PROPERTY_TIME_SCALE,
	/** %掉宝加成 */
	EOM_MODIFIER_PLAYER_PROPERTY_DROP_CHANCE_PERCENTAGE,
	/** %$team掉宝加成 */
	EOM_MODIFIER_TEAM_PROPERTY_DROP_CHANCE_PERCENTAGE,
	/** 试炼场怪物数量 */
	EOM_MODIFIER_PLAYER_PROPERTY_GOLD_MONSTER_BONUS,
	EOM_MODIFIER_TEAM_PROPERTY_GOLD_MONSTER_BONUS,
	/** %经验值获取 */
	EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE_MULTIPLE,
	/** 复活时间* */
	EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME,
	EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME_PERCENT,
	EOM_MODIFIER_PLAYER_PROPERTY_NPC_RESOURCE_COST_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_NPC_RESOURCE_COST_PERCENTAGE_MULTIPLE,
	/** 圣匣6级装备槽位 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_COUNT_BONUS,
	/** 圣匣6级装备槽位百分比 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_PERCENTAGE,
	/** 3级铸造物槽位 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_2_COUNT_BONUS,
	/** 4级铸造物槽位 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_3_COUNT_BONUS,
	/** 5级铸造物槽位 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_4_COUNT_BONUS,
	/** 圣匣各级铸造物槽位 */
	EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_COUNT_BONUS,
	/** %基础挖宝暴击率 */
	EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE,
	/** %挖宝暴击率增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE_AMPLIFY,
	/** %藏宝图掉落率 */
	EOM_MODIFIER_PROPERTY_PLAYER_TREASURE_MAP_DROP_CHANCE_PERCENTAGE,
	/** %运气之神抽奖暴击率 */
	EOM_MODIFIER_PLAYER_PROPERTY_DRAW_CRIT_CHANCE,
	EOM_MODIFIER_PLAYER_PROPERTY_DRAW_ATTRIBUTE_PENCENTAGE,
	/** 物品合成暴击率 */
	EOM_MODIFIER_PLAYER_PROPERTY_COMBINE_CRIT_CHANCE,
	/** 装备合成暴击率 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIPMENT_COMBINE_CRIT,
	/** 技能书合成暴击率 */
	EOM_MODIFIER_PLAYER_PROPERTY_BOOK_COMBINE_CRIT,
	/** %渔获收益 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_RESOURCE_PENCENTAGE,
	/** %鱼血量百分比 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_HEALTH_PENCENTAGE,
	/** %鱼群刷新间隔 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_SPAWN_INTERVAL,
	/** %纯金鱼收益 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_GOLD_CHANCE_PERCENTAGE,
	/** %鱼池板条箱概率 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_CHEST_PENCENTAGE,
	/** %鱼池神符概率 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_RUNE_PENCENTAGE,
	/** %鱼池事件出现概率 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_BUFF_CHANCE_PERCENTAGE,
	/** %渔获消耗降低 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_COST_REDUCTION,
	/** %伐木斧升级需求降低 */
	EOM_MODIFIER_PLAYER_PROPERTY_AXE_EXP_REDUCTION,
	/** %钓鱼竿升级需求降低 */
	EOM_MODIFIER_PLAYER_PROPERTY_FISH_EXP_REDUCTION,
	/** %铁铲升级需求降低 */
	EOM_MODIFIER_PLAYER_PROPERTY_DIG_EXP_REDUCTION,
	/** 开局获得金币 */
	EOM_MODIFIER_PLAYER_PROPERTY_START_GOLD,
	/** 开局获得魂晶 */
	EOM_MODIFIER_PLAYER_PROPERTY_START_CRYSTAL,
	/** 开局获得荣耀 */
	EOM_MODIFIER_PLAYER_PROPERTY_START_SCORE,
	/** %攻击力增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION,
	/** %法术强度增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION,
	/** %生命值增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION,
	EOM_MODIFIER_PLAYER_PROPERTY_ARMOR_AMPLIFICATION,
	/** %力量增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION,
	/** %敏捷增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION,
	/** %智力增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION,
	/** %主属性增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_PRIMARY_AMPLIFICATION,
	/** %次属性增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_SECONDARY_AMPLIFICATION,
	/** %全属性增幅 */
	EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION,
	EOM_MODIFIER_PLAYER_PROPERTY_LOOT_REPLACE,
	EOM_MODIFIER_PLAYER_PROPERTY_STATIC_LOOT,
	/** %局外装备额外掉落几率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DROP_LUCKY,
	/** 局外装备掉落品质幸运值 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_RARITY_LUCKY,
	/** 圣物副本掉落数量 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_GENE_DROP_COUNT,
	/** %挂机经验获取效率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_AFX_EXP_BONUS,
	/** 十二星宫副本单次掉落数量上限 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ZODIAC_DROP_MAX,
	/** 冥渊之器彩色词条概率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_RED,
	/** 契约彩色词条概率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_TICKET_RED,
	EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_OVERWHELMING,
	EOM_MODIFIER_PROPERTY_OVERWHELMING_DAMAGE_MAX_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_OVERWHELMING_DAMAGE_MIN_PERCENTAGE,
	EOM_MODIFIER_PROPERTY_ELECTRIC_DAMAGE_AMPLIFICATION,
	EOM_MODIFIER_PROPERTY_BLIND_PERCENTAGE,
	EOM_MODIFIER_PLAYER_PROPERTY_TRAINING_ALWAYS_SPAWN,
	EOM_MODIFIER_PROPERTY_EQUIP_ATTRIBUTE_PERCENTAGE,
	/** %每级成长属性 */
	EOM_MODIFIER_PLAYER_PROPERTY_GROW_ATTRIBUTE_PENCENTAGE,
	/** 火神之礼锻造属性奖励 */
	EOM_MODIFIER_PLAYER_PROPERTY_INVOKER_REWARD_BONUS_PENCENTAGE,
	/** 炽焰攻速加成 */
	EOM_MODIFIER_PROPERTY_BLAZING_ATTACKSPEED_BONUS_PENCENTAGE,
	/** %防御波次结算经验获取效率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_EXP_PENCENTAGE,
	/** %防御波次结算金币获取效率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_GOLD_PENCENTAGE,
	/** %冥界副本结算经验获取效率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_EXP_PENCENTAGE,
	/** %冥界副本结算火神之锤数量 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_400505_PENCENTAGE,
	/** %冥界副本结算金币获取效率 */
	EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_GOLD_PENCENTAGE,
	/** 每级获得攻击力 */
	EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PER_LEVELUP,
	/** 每级获得法术强度 */
	EOM_MODIFIER_PROPERTY_SPELL_POWER_PER_LEVELUP,
	/** 每级获得智力 */
	EOM_MODIFIER_PROPERTY_INTELLECT_PER_LEVELUP,
	/** 每级获得力量 */
	EOM_MODIFIER_PROPERTY_STRENGTH_PER_LEVELUP,
	/** 每级获得敏捷 */
	EOM_MODIFIER_PROPERTY_AGILITY_PER_LEVELUP,
	/** 每级获得$all */
	EOM_MODIFIER_PROPERTY_STATS_ALL_PER_LEVELUP,
	/** %每级获得击杀全资源 */
	EOM_MODIFIER_PROPERTY_KILL_RESOURCE_PENCENTAGE_PER_LEVELUP,
	/** 英雄每级获得腐蚀值 */
	EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PER_LEVELUP,
	/** %反击几率 */
	EOM_MODIFIER_PROPERTY_COUNTER_CHANCE,
	/** 反击伤害生命值百分比 */
	EOM_MODIFIER_PROPERTY_COUNTER_DAMAGE,
	/** %反击伤害 */
	EOM_MODIFIER_PROPERTY_COUNTER_DAMAGE_PENCENTAGE,
	/** %反击伤害(x) */
	EOM_MODIFIER_PROPERTY_COUNTER_DAMAGE_PENCENTAGE_MULTIPLE,
	EOM_MODIFIER_PROPERTY_STONE_DURATION_BONUS,
	/** 脆弱百分比 */
	EOM_MODIFIER_PROPERTY_FRAIL_PENCENTAGE,
	/** 碾压伤害增强 */
	EOM_MODIFIER_PROPERTY_OVERWHELMING_DAMAGE_AMPLIFICATION,
	/** 亡语属性增强 */
	EOM_MODIFIER_PROPERTY_DEATH_PROPERTY_AMPLIFICATION,
	/** 健壮血量百分比降低 */
	EOM_MODIFIER_PROPERTY_HEALTHY_HEALTH_PERCENTAGE_REDUCE,
	/** 【装备】【主手】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_1_LEVEL,
	/** 【装备】【副手】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_2_LEVEL,
	/** 【装备】【项链】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_3_LEVEL,
	/** 【装备】【戒指】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_4_LEVEL,
	/** 【装备】【腿部】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_5_LEVEL,
	/** 【装备】【护手】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_6_LEVEL,
	/** 【装备】【胸甲】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_7_LEVEL,
	/** 【装备】【头盔】基础等级 */
	EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_8_LEVEL,
	null,
	/** %攻击力增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION_2,
	/** %力量增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION_2,
	/** %敏捷增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION_2,
	/** %智力增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION_2,
	/** %全属性增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION_2,
	/** %法术强度增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION_2,
	/** %生命值增幅II */
	EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION_2,
	/** %物理伤害II */
	EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_2,
	/** %魔法伤害II */
	EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_2,
	/** %暴击伤害II */
	EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_2,
	/** %全队物理伤害II */
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_2,
	/** %全队魔法伤害II */
	EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_2,
	/** %全队暴击伤害II */
	EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_2,
	/** %对精英怪增伤 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_ELITE_ENEMY_PERCENTAGE,
	/** %对首领增伤 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BOSS_ENEMY_PERCENTAGE,
	/** %对普通怪增伤 */
	EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_NORMAL_ENEMY_PERCENTAGE,
	/** %每秒属性收益 */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_SEC_PERCENTAGE,
	/** %击杀属性收益 */
	EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_2,
	EOM_MODIFIER_PROPERTY_LAST,
}
const ATTRIBUTE_MAP: Record<string, EOMModifierFunction> = {
	health: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH,
	health_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_PERCENTAGE,
	teamhero_health_pct: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_HEALTH_PERCENTAGE,
	health_regen: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT,
	health_regen_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_PERCENTAGE,
	health_regen_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_AMPLIFY_PERCENTAGE,
	health_per_str: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_PER_STRENGTH,
	mana: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA,
	mana_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_PERCENTAGE,
	mana_regen: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_REGEN_CONSTANT,
	mana_regen_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_REGEN_PERCENTAGE,
	mana_regen_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_REGEN_AMPLIFY_PERCENTAGE,
	mana_cost_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANACOST_PERCENTAGE,
	attack_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE,
	attack_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PERCENTAGE,
	attack_damage_per_agi: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PER_AGILITY,
	teamhero_attack_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_DAMAGE,
	teamhero_attack_damage_pct: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_DAMAGE_PERCENTAGE,
	attack_accuracy: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_ACCURACY,
	spell_power: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SPELL_POWER,
	spell_power_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SPELL_POWER_PERCENTAGE,
	teamhero_spell_power: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_SPELL_POWER,
	teamhero_spell_power_pct: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_SPELL_POWER_PERCENTAGE,
	int_spell_power: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INTELLECT_SPELL_POWER,
	armor: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR,
	armor_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_PERCENTAGE,
	ignore_armor: EOMModifierFunction.EOM_MODIFIER_PROPERTY_IGNORE_ARMOR,
	ignore_armor_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_PERCENTAGE,
	teamhero_armor: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_ARMOR,
	lifesteal_chance: EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_CHANCE,
	physical_lifesteal: EOMModifierFunction.EOM_MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL,
	magical_lifesteal: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MAGICAL_LIFESTEAL,
	all_lifesteal: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ALL_LIFESTEAL,
	cleave_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CLEAVE_DAMAGE,
	cleave_radius: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CLEAVE_RADIUS,
	attack_speed: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACKSPEED_BONUS,
	max_attack_speed: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MAX_ATTACKSPEED_BONUS,
	teamhero_attack_speed: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACKSPEED_BONUS,
	attack_range: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_RANGE,
	attack_range_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_RANGE_PERCENTAGE,
	teamhero_attack_range: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_ATTACK_RANGE,
	attack_rate: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_RATE,
	cast_range: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CAST_RANGE,
	teamhero_cast_range: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CAST_RANGE,
	strength: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_STRENGTH,
	strength_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_STRENGTH_PERCENTAGE,
	agility: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_AGILITY,
	agility_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_AGILITY_PERCENTAGE,
	intellect: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_INTELLECT,
	intellect_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_INTELLECT_PERCENTAGE,
	teamhero_intellect_pct: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_INTELLECT_PERCENTAGE,
	primary: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_PRIMARY,
	primary_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_PRIMARY_PERCENTAGE,
	all_stats: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_ALL,
	all_stats_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_ALL_PERCENTAGE,
	teamhero_all_stats: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_ALL,
	outgoing_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE,
	outgoing_adaptive_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ADAPTIVE_DAMAGE_PERCENTAGE,
	physical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE,
	magical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE,
	outgoing_damage_per_faith: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_FAITH,
	outgoing_damage_per_devour: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR,
	outgoing_ability_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ABILITY_DAMAGE_PERCENTAGE,
	outgoing_attack_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ATTACK_DAMAGE_PERCENTAGE,
	final_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_FINAL_DAMAGE,
	teamhero_outgoing_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE,
	teamhero_physical_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE,
	teamhero_magical_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE,
	summoned_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE,
	teamhero_summoned_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE,
	damage_to_training: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_TO_TRAINING,
	summoned_damage_reduction: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_REDUCTION,
	damage_reduce: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_REDUCTION,
	incoming_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE,
	incoming_physical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE,
	incoming_magical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_MAGICAL_DAMAGE_PERCENTAGE,
	damage_block: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_BLOCK,
	crit_chance: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_CHANCE,
	crit_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE,
	teamhero_crit_chance: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_CHANCE,
	teamhero_crit_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE,
	cooldown_reduction: EOMModifierFunction.EOM_MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE,
	evasion: EOMModifierFunction.EOM_MODIFIER_PROPERTY_EVASION_CONSTANT,
	dash_charges: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DASH_CHARGES,
	dash_distance_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DASH_PERCENTAGE,
	dash_distance: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DASH_CONSTANT,
	dash_charge_speed: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DASH_CHARGE_SPEED,
	armor_reduction: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION,
	armor_reduction_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE,
	summoned_attack_speed: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_ATTACKSPEED,
	stun_duration_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STUN_TIME_PERCENTAGE,
	chill_reduce_health_regen_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CHILL_RECUDE_HEALTH_REGEN_PERCENTAGE,
	control_threshold_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CONTROL_THRESHOLD_PERCENTAGE,
	barrier_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BARRIER_PERCENTAGE,
	bleeding_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BLEEDING_DAMAGE_PERCENTAGE,
	bleeding_rate_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BLEEDING_RATE_PERCENTAGE,
	bleeding_duration: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BLEEDING_DURATION,
	bleeding_stack: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BLEEDING_STACK,
	burning_base_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BURNING_BASE_DAMAGE_PERCENTAGE,
	burning_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BURNING_DAMAGE_PERCENTAGE,
	burning_rate_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BURNING_RATE_PERCENTAGE,
	burning_duration: EOMModifierFunction.EOM_MODIFIER_PROPERTY_BURNING_DURATION,
	dot_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DOT_DAMAGE_PERCENTAGE,
	tears_of_athena_modify_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_TEARS_OF_ATHENA_COUNT_MODIFY_PERCENT,
	invis_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_PERCENTAGE,
	invis_damage_reduce: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_REDUCTION,
	invis_armor_reduction_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_ARMOR_REDUCTION_PERCENTAGE,
	damage_immune_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DAMAGE_PERCENTAGE,
	damage_immune_duration_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DURATION_PERCENTAGE,
	kill_gold: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL,
	kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL_PERCENTAGE,
	aries_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ARIES_GOLD_PER_KILL_PERCENTAGE,
	taurus_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TAURUS_GOLD_PER_KILL_PERCENTAGE,
	gemini_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GEMINI_GOLD_PER_KILL_PERCENTAGE,
	cancer_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CANCER_GOLD_PER_KILL_PERCENTAGE,
	leo_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LEO_GOLD_PER_KILL_PERCENTAGE,
	virgo_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_VIRGO_GOLD_PER_KILL_PERCENTAGE,
	libra_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LIBRA_GOLD_PER_KILL_PERCENTAGE,
	scorpio_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORPIO_GOLD_PER_KILL_PERCENTAGE,
	sagittarius_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SAGITTARIUS_GOLD_PER_KILL_PERCENTAGE,
	capricorn_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CAPRICORN_GOLD_PER_KILL_PERCENTAGE,
	aquarius_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AQUARIUS_GOLD_PER_KILL_PERCENTAGE,
	pisces_kill_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PISCES_GOLD_PER_KILL_PERCENTAGE,
	kill_crystal: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL,
	kill_crystal_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL_PERCENTAGE,
	kill_score: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL,
	kill_score_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL_PERCENTAGE,
	kill_resource_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE,
	kill_health: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_KILL,
	kill_attack: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_KILL,
	kill_sp: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_KILL,
	kill_all_attribute: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_KILL,
	kill_strength: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_KILL,
	kill_agility: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_KILL,
	kill_intellect: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_KILL,
	kill_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE,
	strength_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_SEC,
	agility_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_SEC,
	intellect_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_SEC,
	all_attribute_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_SEC,
	health_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_SEC,
	attack_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_SEC,
	sp_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_SEC,
	all_damage_per_min: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DAMAGE_PER_MIN,
	physical_damage_per_min: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PHYSICAL_DAMAGE_PER_MIN,
	magical_damage_per_min: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_MAGICAL_DAMAGE_PER_MIN,
	critical_damage_per_min: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRITICALSTRIKE_DAMAGE_PER_MIN,
	tick_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE,
	team_tick_attribute_pct: EOMModifierFunction.EOM_MODIFIER_TEAM_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE,
	gold_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_SEC,
	crystal_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_SEC,
	score_per_sec: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_SEC,
	tick_resource_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE,
	drop_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DROP_CHANCE_PERCENTAGE,
	team_drop_chance: EOMModifierFunction.EOM_MODIFIER_TEAM_PROPERTY_DROP_CHANCE_PERCENTAGE,
	gold_monster: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_MONSTER_BONUS,
	exp_gain_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE,
	respawn_time: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME,
	respawn_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME_PERCENT,
	devour_equip_count: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_COUNT_BONUS,
	devour_casting_count: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_COUNT_BONUS,
	dig_crit_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE,
	dig_crit_chance_amp: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE_AMPLIFY,
	treasure_map_drop_chance: EOMModifierFunction.EOM_MODIFIER_PROPERTY_PLAYER_TREASURE_MAP_DROP_CHANCE_PERCENTAGE,
	draw_crit_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DRAW_CRIT_CHANCE,
	cmbine_crit_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_COMBINE_CRIT_CHANCE,
	equipment_combine_crit: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIPMENT_COMBINE_CRIT,
	book_combine_crit: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_BOOK_COMBINE_CRIT,
	fish_resource_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_RESOURCE_PENCENTAGE,
	fish_health_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_HEALTH_PENCENTAGE,
	fish_spawn_interval: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_SPAWN_INTERVAL,
	fish_gold_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_GOLD_CHANCE_PERCENTAGE,
	fish_chest_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_CHEST_PENCENTAGE,
	fish_rune_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_RUNE_PENCENTAGE,
	fish_buff_chance: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_BUFF_CHANCE_PERCENTAGE,
	fish_cost_reduce: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_COST_REDUCTION,
	axe_exp_reduce: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AXE_EXP_REDUCTION,
	fish_exp_reduce: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_EXP_REDUCTION,
	dig_exp_reduce: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DIG_EXP_REDUCTION,
	start_gold: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_GOLD,
	start_crystal: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_CRYSTAL,
	start_score: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_SCORE,
	attack_damage_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION,
	spell_power_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION,
	health_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION,
	strength_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION,
	agility_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION,
	intellect_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION,
	primary_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PRIMARY_AMPLIFICATION,
	secondary_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SECONDARY_AMPLIFICATION,
	all_amplification: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION,
	service_drop_lucky: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DROP_LUCKY,
	service_rarity_lucky: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_RARITY_LUCKY,
	service_gene_drop_count: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_GENE_DROP_COUNT,
	service_afk_exp_bonus: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_AFX_EXP_BONUS,
	service_zodiac_drop_max: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ZODIAC_DROP_MAX,
	artifact_red: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_RED,
	artifact_ticket_red: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_TICKET_RED,
	grow_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GROW_ATTRIBUTE_PENCENTAGE,
	service_mainline_settle_exp_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_EXP_PENCENTAGE,
	service_mainline_settle_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_GOLD_PENCENTAGE,
	service_dungeon_settle_exp_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_EXP_PENCENTAGE,
	service_dungeon_settle_400505_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_400505_PENCENTAGE,
	service_dungeon_settle_gold_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_GOLD_PENCENTAGE,
	attack_damage_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PER_LEVELUP,
	spell_power_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SPELL_POWER_PER_LEVELUP,
	int_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INTELLECT_PER_LEVELUP,
	str_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STRENGTH_PER_LEVELUP,
	agi_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_AGILITY_PER_LEVELUP,
	all_attribute_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_ALL_PER_LEVELUP,
	kill_resource_pct_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_KILL_RESOURCE_PENCENTAGE_PER_LEVELUP,
	armor_reduction_per_levelup: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PER_LEVELUP,
	counter_chance: EOMModifierFunction.EOM_MODIFIER_PROPERTY_COUNTER_CHANCE,
	counter_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_COUNTER_DAMAGE,
	death_amplify: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DEATH_PROPERTY_AMPLIFICATION,
	healthy_health_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTHY_HEALTH_PERCENTAGE_REDUCE,
	equip_part_1_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_1_LEVEL,
	equip_part_2_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_2_LEVEL,
	equip_part_3_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_3_LEVEL,
	equip_part_4_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_4_LEVEL,
	equip_part_5_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_5_LEVEL,
	equip_part_6_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_6_LEVEL,
	equip_part_7_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_7_LEVEL,
	equip_part_8_level: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_8_LEVEL,
	attack_damage_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION_2,
	strength_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION_2,
	agility_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION_2,
	intellect_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION_2,
	all_stats_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION_2,
	spell_power_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION_2,
	health_amplification_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION_2,
	physical_damage_2: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_2,
	magical_damage_2: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_2,
	crit_damage_2: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_2,
	teamhero_physical_damage_2: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_2,
	teamhero_magical_damage_2: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_2,
	teamhero_crit_damage_2: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_2,
	elite_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_ELITE_ENEMY_PERCENTAGE,
	boss_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BOSS_ENEMY_PERCENTAGE,
	normal_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_NORMAL_ENEMY_PERCENTAGE,
	sec_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_SEC_PERCENTAGE,
	kill_attribute_pct_2: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_2,
}
const ATTRIBUTE_MULTIPLE_MAP: Record<string, EOMModifierFunction> = {
	health_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_PERCENTAGE_MULTIPLE,
	mana_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_PERCENTAGE_MULTIPLE,
	attack_damage_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PERCENTAGE_MULTIPLE,
	spell_power_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SPELL_POWER_PERCENTAGE_MULTIPLE,
	armor_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_PERCENTAGE_MULTIPLE,
	strength_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_STRENGTH_PERCENTAGE_MULTIPLE,
	agility_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_AGILITY_PERCENTAGE_MULTIPLE,
	intellect_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_INTELLECT_PERCENTAGE_MULTIPLE,
	primary_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_PRIMARY_PERCENTAGE_MULTIPLE,
	all_stats_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_ALL_PERCENTAGE_MULTIPLE,
	outgoing_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE,
	outgoing_adaptive_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ADAPTIVE_DAMAGE_PERCENTAGE_MULTIPLE,
	physical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	magical_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	outgoing_damage_per_faith: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_FAITH_MULTIPLE,
	outgoing_damage_per_devour: EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR_MULTIPLE,
	teamhero_outgoing_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE,
	teamhero_physical_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	teamhero_magical_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE,
	summoned_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE_MULTIPLE,
	incoming_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE_MULTIPLE,
	crit_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE,
	teamhero_crit_damage: EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE,
	armor_reduction_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE,
	invis_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_PERCENTAGE_MULTIPLE,
	invis_armor_reduction_pct: EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE,
	damage_immune_damage: EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DAMAGE_PERCENTAGE_MULTIPLE,
	kill_resource_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE_MULTIPLE,
	kill_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_MULTIPLE,
	tick_attribute_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE_MULTIPLE,
	tick_resource_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE_MULTIPLE,
	exp_gain_pct: EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE_MULTIPLE,
}
const EOMModifierFunctionSettleCallback: Partial<Record<EOMModifierFunction, (a: any, b: any) => any>> = {
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_AMPLIFY_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_REDUCTION_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEAL_REDUCTION_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEAL_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_REGEN_AMPLIFY_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANA_REGEN_REDUCTION_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MANACOST_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_SPELL_POWER_PERCENTAGE]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PROCATTACK_BONUS_DAMAGE_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUPPRESS_CLEAVE]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_CANNOT_MISS]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_SPELL_POWER_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_IGNORE_ARMOR_PERCENTAGE_TARGET]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_REDUCTION_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PHYSICAL_LIFESTEAL_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MAGICAL_LIFESTEAL_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACKSPEED_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_FIXED_ATTACK_RANGE]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_FIXED_BASE_ATTACK_RANGE]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_FIXED_BASE_ATTACK_RATE]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PHYSICAL_CONVERT_TO_MAGICAL]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_MAGICAL_CONVERT_TO_PHYSICAL]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_STRENGTH_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_AGILITY_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_INTELLECT_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_PRIMARY_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_STATS_ALL_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ADAPTIVE_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_FAITH_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_SUMMONED_DAMAGE_REDUCTION]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_REDUCTION]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_PHYSICAL_DAMAGE_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INCOMING_MAGICAL_DAMAGE_PERCENTAGE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_NON_LETHAL]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_CRITICALSTRIKE_DAMAGE_TARGET_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_FIXED_CRITICALSTRIKE_CHANCE]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_NO_CRITICALSTRIKE]: MaximumSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_COOLDOWN_PERCENTAGE]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_EVASION_CONSTANT]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ARMOR_REDUCTION_PERCENTAGE_TARGET_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_SOUND_SET]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_SOUND]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PROJECTILE_IMPACT_SOUND]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_DAMAGE_REDUCTION]: CompoundDecreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_INVISIBILITY_ARMOR_REDUCTION_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DAMAGE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_NPC_RESOURCE_COST_PERCENTAGE_MULTIPLE]: CompoundIncreaseSimple,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LOOT_REPLACE]: FirstSimple,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_COUNTER_CHANCE]: CompoundDecrease,
}
const EOMModifierFunctionType: Partial<Record<EOMModifierFunction, EOMModifierPropertyType>> = {
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_HEALTH_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_INTELLECT_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_STATS_ALL]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_SUMMONED_DAMAGE_PERCENTAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_MULTIPLE]: EOMModifierPropertyType.TEAM_HERO,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ARIES_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TAURUS_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GEMINI_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CANCER_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LEO_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_VIRGO_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LIBRA_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORPIO_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SAGITTARIUS_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CAPRICORN_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AQUARIUS_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PISCES_GOLD_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_RESOURCE_PER_KILL_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_KILL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_STRENGTH_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_AGILITY_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_INTELLECT_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATS_ALL_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SP_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DAMAGE_PER_MIN]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PHYSICAL_DAMAGE_PER_MIN]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_MAGICAL_DAMAGE_PER_MIN]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRITICALSTRIKE_DAMAGE_PER_MIN]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_TEAM_PROPERTY_TICK_TIME_ATTRIBUTE_PERCENTAGE]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_CRYSTAL_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SCORE_PER_SEC]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TICK_TIME_RESOURCE_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TIME_SCALE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DROP_CHANCE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_TEAM_PROPERTY_DROP_CHANCE_PERCENTAGE]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GOLD_MONSTER_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_TEAM_PROPERTY_GOLD_MONSTER_BONUS]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EXP_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_REPSPAWN_TIME_PERCENT]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_NPC_RESOURCE_COST_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_NPC_RESOURCE_COST_PERCENTAGE_MULTIPLE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_COUNT_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_2_COUNT_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_3_COUNT_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_4_COUNT_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_CASTING_COUNT_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DIG_CRIT_CHANCE_AMPLIFY]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PLAYER_TREASURE_MAP_DROP_CHANCE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DRAW_CRIT_CHANCE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DRAW_ATTRIBUTE_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_COMBINE_CRIT_CHANCE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIPMENT_COMBINE_CRIT]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_BOOK_COMBINE_CRIT]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_RESOURCE_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_HEALTH_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_SPAWN_INTERVAL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_GOLD_CHANCE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_CHEST_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_RUNE_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_BUFF_CHANCE_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_FISH_COST_REDUCTION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_GOLD]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_CRYSTAL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_START_SCORE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ARMOR_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_PRIMARY_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SECONDARY_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_LOOT_REPLACE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATIC_LOOT]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DROP_LUCKY]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_RARITY_LUCKY]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_GENE_DROP_COUNT]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_AFX_EXP_BONUS]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ZODIAC_DROP_MAX]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_RED]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_ARTIFACT_TICKET_RED]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_TRAINING_ALWAYS_SPAWN]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_GROW_ATTRIBUTE_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_INVOKER_REWARD_BONUS_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_EXP_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_GOLD_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_EXP_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_400505_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_GOLD_PENCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_1_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_2_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_3_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_4_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_5_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_6_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_7_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_8_LEVEL]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTACK_DAMAGE_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STRENGTH_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_AGILITY_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_INTELLECT_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ALL_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SPELL_POWER_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_HEALTH_AMPLIFICATION_2]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_PHYSICAL_DAMAGE_PERCENTAGE_2]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_OUTGOING_MAGICAL_DAMAGE_PERCENTAGE_2]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_TEAMHERO_PROPERTY_CRITICALSTRIKE_DAMAGE_2]: EOMModifierPropertyType.TEAM,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_SEC_PERCENTAGE]: EOMModifierPropertyType.PLAYER,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_KILL_PERCENTAGE_2]: EOMModifierPropertyType.PLAYER,
}
const EOMModifierFunctionCheckValueCallback: Partial<Record<EOMModifierFunction, (value: any, tParams?: any) => any>> = {
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_AMPLIFY_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_REDUCTION_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEAL_AMPLIFY_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEAL_REDUCTION_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_AMPLIFY_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_LIFESTEAL_REDUCTION_PERCENTAGE]: math.abs,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_NON_LETHAL]: PCVC_NonLethal,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PRE_PHYSICAL_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PRE_MAGICAL_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PRE_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PHYSICAL_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MAGICAL_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_ADJUST]: PCVC_DamageAdjust,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_PHYSICAL_DAMAGE_BARRIER]: PCVC_DamageBarrier,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_MAGICAL_DAMAGE_BARRIER]: PCVC_DamageBarrier,
	[EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_BARRIER]: PCVC_DamageBarrier,
	[EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_STATIC_LOOT]: PCVC_StaticLoot,
}

/** $hp_regen */
function GetHealthRegenConstant(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_REGEN_CONSTANT, params);
}
/** 每点力量提供生命值 */
function GetHealthPerStrength(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_HEALTH_PER_STRENGTH, params);
}
/** 每点敏捷提供攻击力 */
function GetAttackDamagePerAgility(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_DAMAGE_PER_AGILITY, params);
}
/** %攻击必中率 */
function GetAttackAccuracy(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_ATTACK_ACCURACY, params);
}
/** %圣匣中每件6级装备伤害提升 */
function GetOutgoingDamagePercentagePerDevour(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_PERCENTAGE_PER_DEVOUR, params);
}
/** %技能伤害 */
function GetOutgoingAbilityDamagePercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ABILITY_DAMAGE_PERCENTAGE, params);
}
/** %攻击伤害 */
function GetOutgoingAttackDamagePercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_ATTACK_DAMAGE_PERCENTAGE, params);
}
/** 税后格挡 */
function GetDamageBlock(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_BLOCK, params);
}
/** 冲刺最大充能 */
function GetDashCharges(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_DASH_CHARGES, params);
}
/** %降低冻结单位生命恢复 */
function GetChillRecudeHealthRegenPercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_CHILL_RECUDE_HEALTH_REGEN_PERCENTAGE, params);
}
/** %流血治疗 */
function GetBleedingLifesteal(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_BLEEDING_LIFESTEAL, params);
}
/** %<damage_immune:伤害免疫/>持续时间 */
function GetDamageImmuneDurationPercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_DAMAGE_IMMUNE_DURATION_PERCENTAGE, params);
}
/** 圣匣6级装备槽位百分比 */
function GetDevourEquipmentPercentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_DEVOUR_EQUIPMENT_PERCENTAGE);
}
/** %防御波次结算经验获取效率 */
function GetServiceMainlineSettleExpPencentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_EXP_PENCENTAGE);
}
/** %防御波次结算金币获取效率 */
function GetServiceMainlineSettleGoldPencentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_MAINLINE_SETTLE_GOLD_PENCENTAGE);
}
/** %冥界副本结算经验获取效率 */
function GetServiceDungeonSettleExpPencentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_EXP_PENCENTAGE);
}
/** %冥界副本结算火神之锤数量 */
function GetServiceDungeonSettle400505Pencentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_400505_PENCENTAGE);
}
/** %冥界副本结算金币获取效率 */
function GetServiceDungeonSettleGoldPencentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_SERVICE_DUNGEON_SETTLE_GOLD_PENCENTAGE);
}
/** 【装备】【主手】基础等级 */
function GetEquipPart1Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_1_LEVEL);
}
/** 【装备】【副手】基础等级 */
function GetEquipPart2Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_2_LEVEL);
}
/** 【装备】【项链】基础等级 */
function GetEquipPart3Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_3_LEVEL);
}
/** 【装备】【戒指】基础等级 */
function GetEquipPart4Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_4_LEVEL);
}
/** 【装备】【腿部】基础等级 */
function GetEquipPart5Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_5_LEVEL);
}
/** 【装备】【护手】基础等级 */
function GetEquipPart6Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_6_LEVEL);
}
/** 【装备】【胸甲】基础等级 */
function GetEquipPart7Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_7_LEVEL);
}
/** 【装备】【头盔】基础等级 */
function GetEquipPart8Level(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_EQUIP_PART_8_LEVEL);
}
/** %对精英怪增伤 */
function GetOutgoingDamageEliteEnemyPercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_ELITE_ENEMY_PERCENTAGE, params);
}
/** %对首领增伤 */
function GetOutgoingDamageBossEnemyPercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_BOSS_ENEMY_PERCENTAGE, params);
}
/** %对普通怪增伤 */
function GetOutgoingDamageNormalEnemyPercentage(unit: CDOTA_BaseNPC, params?: any) {
	return GetModifierProperty(unit, EOMModifierFunction.EOM_MODIFIER_PROPERTY_OUTGOING_DAMAGE_NORMAL_ENEMY_PERCENTAGE, params);
}
/** %每秒属性收益 */
function GetAttributePerSecPercentage(playerID: PlayerID) {
	return GetModifierProperty(playerID, EOMModifierFunction.EOM_MODIFIER_PLAYER_PROPERTY_ATTRIBUTE_PER_SEC_PERCENTAGE);
}