local ____lualib = require("lualib_bundle")
local __TS__Class = ____lualib.__TS__Class
local __TS__ClassExtends = ____lualib.__TS__ClassExtends
local __TS__DecorateLegacy = ____lualib.__TS__DecorateLegacy
local __TS__New = ____lualib.__TS__New
local __TS__SourceMapTraceBack = ____lualib.__TS__SourceMapTraceBack
__TS__SourceMapTraceBack(debug.getinfo(1).short_src, {["9"] = 1,["10"] = 1,["11"] = 3,["12"] = 3,["13"] = 4,["14"] = 5,["15"] = 6,["16"] = 7,["17"] = 8,["18"] = 9,["19"] = 10,["20"] = 11,["21"] = 12,["22"] = 13,["23"] = 14,["24"] = 15,["25"] = 16,["26"] = 17,["27"] = 18,["28"] = 19,["29"] = 20,["30"] = 21,["31"] = 22,["32"] = 23,["33"] = 24,["34"] = 25,["35"] = 26,["36"] = 27,["37"] = 28,["38"] = 29,["39"] = 30,["40"] = 31,["41"] = 32,["42"] = 33,["43"] = 34,["44"] = 35,["45"] = 36,["46"] = 37,["47"] = 38,["48"] = 39,["49"] = 40,["50"] = 41,["51"] = 42,["52"] = 43,["53"] = 44,["54"] = 45,["55"] = 46,["56"] = 47,["57"] = 48,["58"] = 49,["59"] = 50,["60"] = 51,["61"] = 52,["62"] = 53,["63"] = 54,["64"] = 55,["65"] = 56,["66"] = 57,["67"] = 58,["68"] = 60,["69"] = 61,["70"] = 62,["71"] = 63,["72"] = 64,["73"] = 65,["74"] = 66,["75"] = 67,["76"] = 68,["77"] = 69,["78"] = 70,["79"] = 71,["80"] = 72,["81"] = 73,["82"] = 74,["83"] = 75,["84"] = 76,["85"] = 77,["86"] = 78,["87"] = 79,["88"] = 80,["89"] = 81,["90"] = 82,["91"] = 83,["92"] = 84,["93"] = 86,["94"] = 87,["95"] = 88,["96"] = 89,["97"] = 90,["99"] = 92,["100"] = 93,["102"] = 95,["104"] = 5,["105"] = 3,["106"] = 103,["107"] = 104});
local ____exports = {}
local ____tstl_2Dutils = require("lib.tstl-utils")
local reloadable = ____tstl_2Dutils.reloadable
local MSettings = __TS__Class()
MSettings.name = "MSettings"
__TS__ClassExtends(MSettings, CModule)
function MSettings.prototype.init(self, reload)
    if IsServer() then
        local GameMode = GameRules:GetGameModeEntity()
        GameMode:SetInnateMeleeDamageBlockAmount(0)
        GameMode:SetInnateMeleeDamageBlockPerLevelAmount(0)
        GameMode:SetInnateMeleeDamageBlockPercent(0)
        GameMode:SetUnseenFogOfWarEnabled(false)
        GameRules:SetHeroRespawnEnabled(true)
        GameMode:SetFogOfWarDisabled(false)
        GameMode:SetFixedRespawnTime(1)
        GameRules:SetCustomGameAllowBattleMusic(false)
        GameRules:SetCustomGameAllowHeroPickMusic(false)
        GameRules:SetCustomGameAllowMusicAtGameStart(true)
        GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_GOODGUYS, 4)
        GameRules:SetCustomGameTeamMaxPlayers(DOTA_TEAM_BADGUYS, 0)
        GameRules:SetFirstBloodActive(false)
        GameRules:SetGoldPerTick(0)
        GameRules:SetGoldTickTime(99999)
        GameRules:SetHeroSelectionTime(0)
        GameRules:SetHeroSelectPenaltyTime(0)
        GameRules:SetHideKillMessageHeaders(true)
        GameRules:SetPostGameTime(3000)
        GameRules:SetPreGameTime(0)
        GameRules:SetSameHeroSelectionEnabled(true)
        GameRules:SetShowcaseTime(0)
        GameRules:SetStartingGold(0)
        GameRules:SetStrategyTime(0)
        GameRules:SetTimeOfDay(0.26)
        GameRules:SetUseBaseGoldBountyOnHeroes(false)
        GameRules:SetUseCustomHeroXPValues(true)
        GameRules:SetSuggestItemsEnabled(false)
        GameMode:DisableHudFlip(true)
        GameMode:SetAlwaysShowPlayerNames(false)
        GameMode:SetAnnouncerDisabled(true)
        GameMode:SetCameraZRange(0, 20000)
        GameMode:SetCustomBackpackCooldownPercent(1)
        GameMode:SetCustomBackpackSwapCooldown(0)
        GameMode:SetCustomBuybackCooldownEnabled(true)
        GameMode:SetCustomBuybackCostEnabled(true)
        GameMode:SetBuybackEnabled(false)
        GameMode:SetCameraDistanceOverride(1300)
        GameMode:SetCustomGameForceHero("npc_dota_hero_axe")
        GameMode:SetUseCustomHeroLevels(true)
        GameMode:SetCustomHeroMaxLevel(100)
        GameMode:SetCustomXPRequiredToReachNextLevel({0, 10000})
        GameMode:SetDaynightCycleDisabled(true)
        GameMode:SetDeathOverlayDisabled(true)
        GameMode:SetGoldSoundDisabled(false)
        GameMode:SetSendToStashEnabled(false)
        GameMode:SetCanSellAnywhere(false)
        GameMode:SetAllowNeutralItemDrops(false)
        GameMode:SetRandomHeroBonusItemGrantDisabled(true)
        GameMode:SetRecommendedItemsDisabled(true)
        GameMode:SetNeutralStashEnabled(false)
        GameMode:SetHudCombatEventsDisabled(true)
        GameMode:SetKillingSpreeAnnouncerDisabled(true)
        GameMode:SetLoseGoldOnDeath(false)
        GameMode:SetMaximumAttackSpeed(5000)
        GameMode:SetMinimumAttackSpeed(1)
        GameMode:SetPauseEnabled(true)
        GameMode:SetRecommendedItemsDisabled(true)
        GameMode:SetSelectionGoldPenaltyEnabled(false)
        GameMode:SetStashPurchasingDisabled(true)
        GameMode:SetStickyItemDisabled(true)
        GameMode:SetTPScrollSlotItemOverride("item_back")
        GameMode:SetGiveFreeTPOnDeath(false)
        GameMode:SetWeatherEffectsDisabled(true)
        GameMode:SetForcedHUDSkin("default")
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_STRENGTH_DAMAGE, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_STRENGTH_HP, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_STRENGTH_HP_REGEN, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_AGILITY_DAMAGE, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_AGILITY_ARMOR, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_AGILITY_ATTACK_SPEED, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_INTELLIGENCE_DAMAGE, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_INTELLIGENCE_MANA, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_INTELLIGENCE_MANA_REGEN, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_INTELLIGENCE_MAGIC_RESIST, 0)
        GameMode:SetCustomAttributeDerivedStatValue(DOTA_ATTRIBUTE_ALL_DAMAGE, 0)
        GameMode:SetGoldSoundDisabled(true)
        if IsInToolsMode() then
            GameRules:LockCustomGameSetupTeamAssignment(false)
            GameRules:EnableCustomGameSetupAutoLaunch(false)
            GameRules:SetCustomGameSetupAutoLaunchDelay(3)
        else
            GameRules:LockCustomGameSetupTeamAssignment(false)
            GameRules:EnableCustomGameSetupAutoLaunch(true)
        end
        GameRules:SetUseUniversalShopMode(true)
    end
end
MSettings = __TS__DecorateLegacy({reloadable}, MSettings)
if _G.Settings == nil then
    _G.Settings = __TS__New(MSettings)
end
return ____exports
